---
- name: Enable elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes

- name: Start elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    state: started

- name: Enable kibana service
  ansible.builtin.systemd:
    name: kibana
    daemon_reload: yes
    enabled: yes

- name: Start kibana service
  ansible.builtin.systemd:
    name: kibana
    state: restarted