---
# tasks file for elasticsearch
- name: "Check target platform"
  ansible.builtin.fail:
    msg: This platform doesn't yet supported
  when: ansible_system != "Linux"

- name: "Check target OS"
  ansible.builtin.fail:
    msg: This OS doesn't yet supported
  when:
    - ansible_os_family != 'RedHat'
    - ansible_os_family != 'Debian'

- include_tasks: RedHat-specific.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian-specific.yml
  when: ansible_os_family == 'Debian'

- name: "Copy elasticsearch config"
  ansible.builtin.template:
    src: "{{ elasticsearch_config_template }}"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    group: "{{ elasticsearch_default_group }}"
  notify: Start elasticsearch service

- name: "Copy kibana config"
  ansible.builtin.template:
    src: "{{ kibana_config_template }}"
    dest: "/etc/kibana/kibana.yml"
    group: "{{ kibana_default_group }}"
  notify: Start kibana service

