---
- name: "CentOS 8 | Disable default repo"
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  when: ansible_distribution_major_version == 8

- name: "Add Fluent-bit RPM repository"
  ansible.builtin.yum_repository:
    name: Fluent-Bit
    description: Fluent Bit repository
    baseurl: https://packages.fluentbit.io/centos/$releasever/$basearch/
    gpgcheck: true
    gpgkey: "{{ fluentbit_repo_key_url }}"
    enabled: yes

- name: "Installing Fluent-bit from the RPM repository"
  ansible.builtin.yum:
    update_cache: true
    name: fluent-bit
    state: latest
  notify:
    - Enable fluent-bit service
    - Start fluent-bit service

